name: crowdin-pull-b2c

concurrency:
  group: crowdin-b2c

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  pull-from-crowdin:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin action - pull
        uses: crowdin/github-action@v2
        with:
          source: 'packages/ems-booking/web-app/src/internationalization/en.json'                                        # Sources pattern
          translation: '%original_path%/%two_letters_code%.json'    # Translations pattern
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          base_url: https://andriy.crowdin.com
          upload_sources: true
          upload_translations: false
          # upload_translations_args: ''
          download_sources: true
          download_sources_args: --preserve-hierarchy
          download_translations: true
          download_translations_args: --skip-untranslated-strings
          localization_branch_name: l10n-crowdin-master-b2c
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations B2C'
          pull_request_body: 'New Crowdin translations pulled by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
